server:
  port: 8084
spring:
    datasource:
        name: DAQ
        url: jdbc:mysql://192.168.0.18:3306/realtime_people?useUnicode=true&characterEncoding=UTF8&autoReconnect=true
        username: realtime_people
        password: DaqsoftUniver2016!
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        MapUnderscoreToCamelCase: true
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    kafka:
      bootstrap-servers: 192.168.2.114:9092
      consumer:
        group-id: log-collcetor
      template:
        default-topic: test
      listener:
        concurrency: 2
com:
  cloudera:
    hdfs:
      url:  hdfs://192.168.100.178:9000